BEGIN TRANSACTION;
DROP TABLE IF EXISTS "商品";
CREATE TABLE "商品" (
	"No"	INTEGER NOT NULL UNIQUE,
	"商品コード"	TEXT NOT NULL UNIQUE,
	"品名"	TEXT NOT NULL,
	"数量"	INTEGER NOT NULL
);
INSERT INTO "商品" VALUES (1,'A100','テスト商品',30);
INSERT INTO "商品" VALUES (2,'B12','テスト',20);
COMMIT;
